### ISSUE TITLE
Font Colour

### ISSUE THREAD

**Issue by afreenpoly** [kolhesatish/GifAPI#1]
Due to the fact that you  added below code in your body class in  **global.css** the font color was white it wasnt showing up . It was also not showing up in the search bar.

```
  color: rgb(var(--foreground-rgb));
```
![image](https://github.com/kolhesatish/GifAPI/assets/85273664/54a7f04d-f2d7-45a8-88a7-09c85c984e23)
![image](https://github.com/kolhesatish/GifAPI/assets/85273664/db8c58d4-63a5-41c5-bec3-9f3a4d90a89b)

i have corrected the above,edit the following lines in corresponding files
1.Navbar.jsx
```
<div>
          <p id="navp">Welcome, {user.displayName}</p>
          <p id="navp" className="cursor-pointer" onClick={handleSignOut}>
            Sign out
          </p>
        </div>
```
2.SearchBar.jsx
```
<input
          type="text"
          id="search"
          name="search"
          value={searchQuery}
          onChange={handleSearchChange}
          className="border border-gray-300 p-2 rounded-md w-full mr-2 navp"
        />
```
3.global.css
```
label,#search {
  color: #333; 
} 

p {
  color: #333; 
}

#navp {
  color: white;
}
```
which should have made the issue clear
![image](https://github.com/kolhesatish/GifAPI/assets/85273664/2fff882e-149c-480e-a074-f2b28a282aed)

**Comment by kolhesatish** [comment]
I fix this, Thank You.
